blank_issues_enabled: false
contact_links:
  - name: MisakaNet Discussion
    url: https://github.com/Ikalus1988/MisakaNet/discussions
    about: Please ask questions and discuss in the GitHub Discussions tab
<<<ENDFILE<<<
