#!/usr/bin/env python3
"""MisakaNet Site Health Snapshot — records frontend/Worker health before each release.

Usage: python scripts/site_health_check.py [--base-url URL]

Outputs a markdown snapshot to docs/maintainer/site-health-YYYY-MM-DD.md
"""

import argparse
import datetime
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_BASE = "https://misakanet.dev"

ENDPOINTS = [
    ("Homepage", "/"),
    ("API Health", "/api/health"),
    ("API Counter", "/api/counter"),
    ("API Lessons", "/api/lessons"),
    ("Journey Page", "/journey"),
    ("Search UI", "/search"),
]

UI_CHECKS = [
    ("Registration entry", "register", ["register", "sign up", "join"]),
    ("Search UI", "search", ["search", "query"]),
    ("Onboarding modal", "onboarding", ["onboarding", "get started", "welcome"]),
    ("Journey link", "journey", ["journey"]),
]


def check_endpoint(base: str, path: str, timeout: int = 15) -> dict:
    """Check a single endpoint and return status info."""
    url = f"{base.rstrip('/')}{path}"
    result = {"url": url, "path": path, "status": "❓", "code": None, "latency_ms": None, "notes": ""}
    try:
        start = datetime.datetime.now()
        req = urllib.request.Request(url, headers={"User-Agent": "MisakaNet-HealthCheck/1.0"})
        resp = urllib.request.urlopen(req, timeout=timeout)
        elapsed = (datetime.datetime.now() - start).total_seconds() * 1000
        body = resp.read().decode("utf-8", errors="replace")[:2000]
        result["code"] = resp.getcode()
        result["latency_ms"] = round(elapsed, 1)
        if resp.getcode() < 400:
            result["status"] = "✅"
        else:
            result["status"] = "⚠️"
            result["notes"] = f"HTTP {resp.getcode()}"
    except urllib.error.HTTPError as e:
        result["status"] = "⚠️"
        result["code"] = e.code
        result["notes"] = f"HTTP {e.code}"
    except urllib.error.URLError as e:
        result["status"] = "❌"
        result["notes"] = f"Connection error: {e.reason}"
    except Exception as e:
        result["status"] = "❌"
        result["notes"] = str(e)
    return result


def generate_snapshot(base: str, output_path: str | None = None) -> str:
    """Generate the site health snapshot and return markdown."""
    today = datetime.date.today().isoformat()
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append(f"# Site Health Snapshot — {today}")
    lines.append("")
    lines.append(f"**Generated:** {now}")
    lines.append(f"**Base URL:** {base}")
    lines.append("")
    lines.append("## Endpoint Health")
    lines.append("")
    lines.append("| Endpoint | Status | Code | Latency | Notes |")
    lines.append("|----------|--------|------|---------|-------|")

    warnings = []
    for label, path in ENDPOINTS:
        result = check_endpoint(base, path)
        lines.append(
            f"| {label} | {result['status']} | {result['code'] or '-'} | "
            f"{result['latency_ms']}ms | {result['notes']} |"
        )
        if result["status"] in ("⚠️", "❌"):
            warnings.append(f"- **{label}** ({path}): {result['notes'] or result['status']}")

    lines.append("")
    lines.append("## UI Element Checks")
    lines.append("")
    lines.append("| Element | Expected Keywords | Status | Notes |")
    lines.append("|---------|------------------|--------|-------|")

    # Check homepage for UI elements
    hp_result = check_endpoint(base, "/")
    hp_body = ""
    if hp_result["code"] and hp_result["code"] < 400:
        try:
            req = urllib.request.Request(f"{base.rstrip('/')}/", headers={"User-Agent": "MisakaNet-HealthCheck/1.0"})
            resp = urllib.request.urlopen(req, timeout=15)
            hp_body = resp.read().decode("utf-8", errors="replace").lower()
        except Exception:
            pass

    for label, path, keywords in UI_CHECKS:
        if hp_body:
            found = any(kw.lower() in hp_body for kw in keywords)
            status = "✅" if found else "⚠️"
            note = "" if found else f"Keywords not found: {keywords}"
        else:
            status = "❌"
            note = "Homepage not reachable"
        lines.append(f"| {label} | {', '.join(keywords[:2])}... | {status} | {note} |")
        if status in ("⚠️", "❌"):
            warnings.append(f"- **{label}**: {note}")

    lines.append("")
    if warnings:
        lines.append("## ⚠️ Warnings")
        lines.append("")
        for w in warnings:
            lines.append(w)
    else:
        lines.append("## ✅ No Warnings")
        lines.append("")
        lines.append("All checks passed.")

    lines.append("")
    lines.append("---")
    lines.append(f"*Snapshot generated by `scripts/site_health_check.py`*")

    markdown = "\n".join(lines) + "\n"

    # Optionally write to file
    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(markdown)
        print(f"Snapshot written to: {output_path}")

    return markdown


def main():
    parser = argparse.ArgumentParser(description="Generate MisakaNet site health snapshot")
    parser.add_argument("--base-url", default=DEFAULT_BASE, help=f"Base URL (default: {DEFAULT_BASE})")
    parser.add_argument("--output", "-o", help="Output file path (default: docs/maintainer/site-health-YYYY-MM-DD.md)")
    args = parser.parse_args()

    if not args.output:
        repo_root = Path(__file__).resolve().parent.parent
        today = datetime.date.today().isoformat()
        args.output = str(repo_root / "docs" / "maintainer" / f"site-health-{today}.md")

    markdown = generate_snapshot(args.base_url, args.output)
    print(markdown)


if __name__ == "__main__":
    main()
